# Generated by Django 4.0.5 on 2022-06-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofia_weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribedusers',
            options={'verbose_name_plural': 'SubscribedUsers'},
        ),
    ]
